### ISSUE TITLE
Peer authentication failed for user "dot_ledger"

### ISSUE THREAD

**Issue by zimmertr** [dotledger/dotledger#4]
Hello, I have been trying to get this installed for the past few hours and no matter what I do I receive the following error for each of the databases when I run $bundle exec rake db:setup

```
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"dot_ledger_test", "pool"=>5, "username"=>"dot_ledger", "password"=>">redacted<"}
-- enable_extension("plpgsql")
rake aborted!
PG::ConnectionBad: FATAL:  Peer authentication failed for user "dot_ledger"
```

I have ensured that the password that I have inserted into config/database.yml is the same password for the postgres user account as well. The entire dot_ledger directory is owned by postgres, which is the user that is calling the above command.

**Comment by Chouchen** [comment]
Same goes for me

**Comment by kaleworsley** [comment]
This sounds like a postgres authentication issue. Maybe this will help http://stackoverflow.com/questions/18664074/getting-error-peer-authentication-failed-for-user-postgres-when-trying-to-ge.
